resource "aws_alb" "alb" {
  count              = var.create_alb == true ? 1 : 0
  name               = "alb-${var.name}"
  subnets            = [var.subnets[0], var.subnets[1]]
  security_groups    = [var.security_group]
  load_balancer_type = "application"
  internal           = false
  enable_http2       = true
  idle_timeout       = 30
}

# ------- ALB Listenet for HTTPS -------
resource "aws_alb_listener" "https_listener" {
  count             = var.create_alb == true ? (var.enable_https == true ? 1 : 0) : 0
  load_balancer_arn = aws_alb.alb[0].id
  port              = "443"
  protocol          = "HTTPS"

  default_action {
    target_group_arn = var.target_group
    type             = "forward"
  }

  lifecycle {
    // to avoid changes generated by CodeDeploy changes
    ignore_changes = [default_action]
  }
}

# ------- ALB Listener for HTTP -------
resource "aws_alb_listener" "http_listener" {
  count             = var.create_alb == true ? 1 : 0
  load_balancer_arn = aws_alb.alb[0].id
  port              = "80"
  protocol          = "HTTP"

  default_action {
    target_group_arn = var.target_group
    type             = "forward"
  }

  lifecycle {
    // to avoid changes generated by CodeDeploy changes
    ignore_changes = [default_action]
  }
}
# ------- First Target Group for ALB -------  
resource "aws_alb_target_group" "target_group_1" {  
  count                = var.create_target_group_1 == true ? 1 : 0  
  name                 = "${var.name}-tg-1"  
  port                 = var.port_1  
  protocol             = var.protocol_1  
  vpc_id               = var.vpc  
  target_type          = var.tg_type_1  
  deregistration_delay = var.deregistration_delay_1  
  
  health_check {  
    enabled             = true  
    interval            = var.health_check_interval_1  
    path                = var.health_check_path_1  
    port                = var.health_check_port_1  
    protocol            = var.protocol_1  
    timeout             = var.health_check_timeout_1  
    healthy_threshold   = var.healthy_threshold_1  
    unhealthy_threshold = var.unhealthy_threshold_1  
    matcher             = var.health_check_matcher_1  
  }  
  
  lifecycle {  
    create_before_destroy = true  
  }  
}  
  
# ------- Second Target Group for ALB -------  
resource "aws_alb_target_group" "target_group_2" {  
  count                = var.create_target_group_2 == true ? 1 : 0  
  name                 = "${var.name}-tg-2"  
  port                 = var.port_2  
  protocol             = var.protocol_2  
  vpc_id               = var.vpc  
  target_type          = var.tg_type_2  
  deregistration_delay = var.deregistration_delay_2  
  
  health_check {  
    enabled             = true  
    interval            = var.health_check_interval_2  
    path                = var.health_check_path_2  
    port                = var.health_check_port_2  
    protocol            = var.protocol_2  
    timeout             = var.health_check_timeout_2  
    healthy_threshold   = var.healthy_threshold_2  
    unhealthy_threshold = var.unhealthy_threshold_2  
    matcher             = var.health_check_matcher_2  
  }  
  
  lifecycle {  
    create_before_destroy = true  
  }  
}  
